# review-epubmaker向けの設定ファイルの例。
# yamlファイルをReVIEWファイルのある場所に置き、
# 「review-epubmaker yamlファイル」を実行すると、<bookname>.epubファイルが
# 生成されます。
# このファイルはUTF-8エンコーディングで記述してください。

# from https://github.com/kmuto/review/blob/master/doc/sample.yaml

# ブック名(ファイル名になるもの。ASCII範囲の文字を使用)
bookname: C89-FirstStepReVIEW-v2
# 書名
booktitle: C89-FirstStepReVIEW-v2
# 著者
aut: TechBooster
prt: TechBooster
prt_url:  http://techbooster.org/
edt: mhidaka
date: 2015-12-31
rights: |
  (C) 2015 TechBooster
description:
# 以下はオプション
#prt: 出版社
# asn: Associated name
# ant: Bibliographic antecedent
# clb: 貢献者
# edt: 編集者
# dsr: デザイナ
# ill: イラストレータ
# pht: 撮影者
# trl: 翻訳者
# date: 刊行日
# rights: 権利表記
# description: ブックの説明
#
# coverfile: カバーページのbody要素内に挿入する内容を記述したファイル名
coverfile: _cover.html
# coverimage: 表紙用画像ファイル
# 固有IDに使用するドメイン
urnid: https://github.com/TechBooster/C89-FirstStepReVIEW-v2
# CSSファイル (yamlファイルおよびReVIEWファイルを置いたディレクトリにあること
stylesheet: stylesheet.css
# LaTeX用のスタイルファイル(styディレクトリ以下に置くこと)
texstyle: techbooster-doujin
# LaTeX用のdocumentclassを指定する
texdocumentclass: ["jsbook", "b5j,twoside,openany"]
# 目次として抽出するレベル
toclevel: 2
# セクション番号を表示するレベル
secnolevel: 2
# EPUBのバージョン(現時点では2または3。デフォルトは2)
epubversion: 3
# HTMLのバージョン(現時点では4または5。デフォルトは4。epubversionを3にした場合は自動で5に設定される)
htmlversion: 5
# 表紙を出力するか
titlepage: true
# 目次を出力するか
toc: true
# EPUB標準の目次以外に目次を作成するか
mytoc: null
# 奥付を作成するか。デフォルトでは作成されない。trueを指定するとデフォルトの奥付、ファイル名を指定するとそれがcolophon.htmlとしてコピーされる
colophon: true
# XHTML生成後に実行するプログラム。$1:HTMLの生成されたディレクトリ $2:ReVIEWファイルのあるディレクトリ $3:起動時指定のyamlファイル名
# posthook: hook.sh
# EPUBで表紙をコンテンツに含めるか。デフォルトでは作成されない。yesにするとiBooks等でも最初に表紙が表示されるようになる
cover_linear: null
# review-compileに渡すパラメータ
params: --stylesheet=sample.css
# デバッグフラグ。nullでないときには一時ファイルをカレントディレクトリに作成し、削除もしない
debug: null
# 子ビルダに渡すパラメータ
params:

history: |
  2015年12月31日  初版発行 v1.0.0
